Define Asset Class Merge
passiv/passiv-web pull request #193
Opened 2020-10-30 19:25 UTC by ShayanAbedi

2020-11-30 20:41 UTC, mikecousins requested changes

2020-11-30 20:41 UTC, mikecousins commented on src/components/ModelAssetClass/AssetClass.tsx
> +import '@reach/dialog/styles.css';
This css file should be imported only once up at a very root file. Usually index.tsx or something. If literally nothing else in the app is ever going to use it this is okay, but if not it can cause really flaky behaviour.

2020-11-30 20:41 UTC, mikecousins commented on src/components/ModelAssetClass/ModelAssetClass.tsx
> +        <BackButton onClick={() => setBack(true)}>
You can replace this with more direct logic by just doing a `history.push('/')`. You'll need to add a `const history = useHistory()` at the top of the component.

2020-11-30 20:41 UTC, mikecousins commented on src/components/ModelAssetClass/Target.tsx
> +  const [enteredSymbol, setEnteredSymbol] = useState(null);
setEnteredSymbol is never used and it's defaulted to null. Should be able to remove this.

2020-11-30 20:41 UTC, mikecousins commented on src/components/ModelPortfolio/AssetClassSelector.tsx
> +import '@reach/combobox/styles.css';
Again you most likely don't want to import css files at this low of a level.

2020-11-30 20:41 UTC, mikecousins commented on src/components/ModelPortfolio/AssetClassSelector.tsx
> +    ); //TODO change the hardcoded groupId
This feels wrong? Can we use their actual group id?

2020-11-30 20:41 UTC, mikecousins commented on src/components/ModelPortfolio/AssetClassesBox.tsx
> +    ); //TODO change the hardcoded groupId
Can we not hardcode this?

2020-11-30 20:41 UTC, mikecousins commented on src/components/ModelPortfolio/ModelPortfolio.tsx
> +import { ViewBtn } from '../../styled/Group';
Not used.

2020-11-30 20:41 UTC, mikecousins commented on src/components/ModelPortfolio/ModelPortfolio.tsx
> +  }, []);
Need to fix up this warning

2020-12-01 14:12 UTC, ShayanAbedi commented on src/components/ModelAssetClass/AssetClass.tsx
> +import '@reach/dialog/styles.css';
thanks. I didn't know that

2021-04-09 12:08 UTC, closed without merging