Zerodha frontend -> integrations
passiv/passiv-web pull request #213
Opened 2021-02-17 13:19 UTC by nickmccullum

2021-02-17 19:37 UTC, brendanwood requested changes

2021-02-17 19:37 UTC, brendanwood commented on src/components/RebalanceWidget/index.tsx
> +    const zerodhaTradeBasket: any = [];
there's a cleaner way to do this where you're not modifying `zerodhaTradeBasket` directly inside your forEach loop. should instead do something like this:
```
const zerodhaTradeBasket: TradeBasketType = trades.trades.map(trade => {
    return {
        variety: 'regular',
        tradingsymbol: trade.universal_symbol.description,
        ...blah blah....
    };
})
```
Having an explicit type is probably helpful here to make sure we're sending in the right object in all cases.

2021-02-17 19:37 UTC, brendanwood commented on src/components/RebalanceWidget/index.tsx
> +  const zerodhaAccounts = groupAccounts.filter(
I don't think this is the proper way to filter by brokerage. You should use the `account.brokerage_authorization` field to lookup the relevant brokerage auth from the authorizations redux field, and then check the associated brokerage slug there.

2021-02-17 19:37 UTC, brendanwood commented on src/components/RebalanceWidget/index.tsx
> +    orderValidation = (
What happens here if more than one Zerodha account is connected?

2021-02-17 19:37 UTC, brendanwood commented on src/pages/AuthorizationPage.tsx
> +      openURL: 'https://kite.trade/connect/login?api_key=pnriechdkzx5ipvq&v=3',
need to add a couple fields here (the structure changed recently). specifically, `defaultConnectionType: 'true',` and `confirmPrompt: null,`

2021-02-18 12:30 UTC, nickmccullum commented on src/components/RebalanceWidget/index.tsx
> +    orderValidation = (
Right now it's not possible for one user to own multiple Zerodha accounts: https://support.zerodha.com/category/your-zerodha-account/your-profile/articles/multiple-trading-accounts#:~:text=No%2C%20you%20can%20only%20open,name%20of%20your%20family%20members.

Previously we had talked about launching assuming people would only pair one account per portfolio group, and adjusting later if that isn't the case

2021-03-23 11:54 UTC, closed without merging